#PYTHON PROGRAM TO REMOVE DUPLICATES FROM LIST OR (STRING)
#PYTHON PROGRAM TO INTERCHANGE FIRST AND LAST ELEMENT IN A LIST

#FIFO INTERNATIONAL/28-12-2023

'''1.WRITE A PROGRAM TO SWAP "WILL" AND "WAY" IN FOLLOWING STRING.
str = "Where there is a will, there is a way" '''

'''2.WRITE A PROGRAM USING CLASS FOR FIBONACCI SERIES IN PYCHARM AND IMPORT/RUN IN ROBOT FRAMEWORK'''

